// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zZuYy93wdh4EmCUn2nVMUUngxsL3pJo',
    appId: '1:664321133517:web:9f898395e6e69492635284',
    messagingSenderId: '664321133517',
    projectId: 'productive360-dbase',
    authDomain: 'productive360-dbase.firebaseapp.com',
    databaseURL: 'https://productive360-dbase-default-rtdb.firebaseio.com',
    storageBucket: 'productive360-dbase.firebasestorage.app',
    measurementId: 'G-VCH0NTHV10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAArqRVKLI-Ygvj9eO6T34EC9Vixmm8YSk',
    appId: '1:664321133517:android:4ee99430db84542c635284',
    messagingSenderId: '664321133517',
    projectId: 'productive360-dbase',
    databaseURL: 'https://productive360-dbase-default-rtdb.firebaseio.com',
    storageBucket: 'productive360-dbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM5BuIkqGBt_0b1aeIyrgmwsA0IddrHEg',
    appId: '1:664321133517:ios:66aceac9be0bf48f635284',
    messagingSenderId: '664321133517',
    projectId: 'productive360-dbase',
    databaseURL: 'https://productive360-dbase-default-rtdb.firebaseio.com',
    storageBucket: 'productive360-dbase.firebasestorage.app',
    iosBundleId: 'com.example.productive360App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM5BuIkqGBt_0b1aeIyrgmwsA0IddrHEg',
    appId: '1:664321133517:ios:66aceac9be0bf48f635284',
    messagingSenderId: '664321133517',
    projectId: 'productive360-dbase',
    databaseURL: 'https://productive360-dbase-default-rtdb.firebaseio.com',
    storageBucket: 'productive360-dbase.firebasestorage.app',
    iosBundleId: 'com.example.productive360App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4zZuYy93wdh4EmCUn2nVMUUngxsL3pJo',
    appId: '1:664321133517:web:f639ad4ef6863300635284',
    messagingSenderId: '664321133517',
    projectId: 'productive360-dbase',
    authDomain: 'productive360-dbase.firebaseapp.com',
    databaseURL: 'https://productive360-dbase-default-rtdb.firebaseio.com',
    storageBucket: 'productive360-dbase.firebasestorage.app',
    measurementId: 'G-0K5JG8XDWE',
  );
}
